### ISSUE TITLE
Getting error on creating question

### ISSUE THREAD

**Issue by hamzahali** [goldhat/quizmaster#133]
Fatal error: Call to undefined function fieldmaster_copy_postmeta() in /home/standardtouch/public_html/wp-content/plugins/quizmaster/quizmaster.php on line 856

**Comment by goldhat** [comment]
v0.6.3 just released has a fix for that, it was a result of the switch to FieldMaster but this version should also support ACF Pro: https://github.com/goldhat/quizmaster/releases/tag/v0.6.3
