### ISSUE TITLE
undefined function

### ISSUE THREAD

**Issue by Kpk1l** [goldhat/quizmaster#139]
I activated Field Master and I created a new field (I dont know if I do it right - you dont have a guide for that)
I activated QuizMaster and create a question and a quiz. On the quiz page I get this error:
`Fatal error: Call to undefined function twentyseventeen_get_svg() in D:\xampp\htdocs\wordpress\wp-content\plugins\quizmaster\templates\quiz.php on line 33`

*and how I find the quiz ID?

**Comment by goldhat** [comment]
Quiz ID is in the address bar (it's the same as the post id for the quiz post) and in the view/edit links. 

This theme error is from one of the templates, already reported on WP support, working on a fix. If you are able to edit your files, search for that function and remove it from the template file.

**Comment by goldhat** [comment]
v0.6.4 should fix the twentyseventeen error, it's released here and on being pushed currently to WP directory.

**Comment by goldhat** [comment]
No response, closing - issue should be well resolved in latest versions.
