### ISSUE TITLE
Unselected Question in Quiz dropdown

### ISSUE THREAD

**Issue by tdamskov** [goldhat/QuizMaster#50]
**How to reproduce:**
Edit Quiz -> Questions tab -> Add row . Don't select anything in the dropdown.
**Expected result:** The empty dropdown should be ignored and not display in the frontend
**Actual result:** The frontend displays a broken question!

**Comment by goldhat** [comment]
I've made the question field required, that should validate an empty row and get us around the problem.

**Comment by goldhat** [comment]
This solution appears to have worked.
