### ISSUE TITLE
Test if revisions are properly referenced by scores

### ISSUE THREAD

**Issue by goldhat** [goldhat/QuizMaster#70]
The scores system should always be referencing revisions, rather than the current post id. Because that way if the post is edited, the reference is still to the correct data stored in association with the revision. 

Test this is the case by taking a test, viewing the scores, taking a note of some of the data. Then edit the quiz and/or questions. Check if the score still shows the correct information. 

This test needs to be run multiple times to account for all the different information. Definitely test quiz/question editing separately at one point to ensure revisions work for both. And make sure edited information is something you could actually see change in the score if it was improperly referenced.

**Comment by tdamskov** [comment]
This seems to be working. When editing and rerunning a quiz or editing the questions, the Quiz Score seems to update the Quiz ID to a new ID (visible in the Quiz Scores overview), and the JSON score data noted for the questions also updates to new ID's if the questions have been edited.
