### ISSUE TITLE
Single Question permits multiple correct

### ISSUE THREAD

**Issue by tdamskov** [goldhat/QuizMaster#81]
How to reproduce:
Create a Single Question, add three Answer rows.
Result: You can select more than one Answer as correct.
Expected result: Only one answer should be selectable as correct.

**Comment by goldhat** [comment]
fixed with new field interface, user can enter only 1 correct answer, and then enters unlimited number of incorrect. It's perhaps not the best UX approach, but it solves the problem. Might consider as enhancement to later go back to the checkboxes, that will require custom JS to control.
