### ISSUE TITLE
Multiple choice Question permits only one answer

### ISSUE THREAD

**Issue by tdamskov** [goldhat/QuizMaster#82]
How to reproduce: Create a Multiple Choice question, add more than one correct answer. Run the Quiz.
Expected result: When the question displays, it should be possible to select more than one question
Actual result: Currently, the question displays with radio buttons, permitting only one answer.

Note: Is the Question type somehow being executed in front as default (single question?)

**Comment by goldhat** [comment]
It was because of field names, all the field names have been "normalized" now which means they use the same prefixes. The version with this change is v1.0.0.
